// ── Cultures data ──
const CULTURES = [
  { id:'ble',   name:'Blé tendre', emoji:'🌾', cat:'cereale', match:88, color:'#2E7D32',
    season:'Oct – Mai', water:'350–500 mm', phRange:'6.0–7.5', npk:'N:120 P:60 K:60 kg/ha',
    desc:'Céréale · Plaine · Semi-aride' },
  { id:'orge',  name:'Orge',       emoji:'🌾', cat:'cereale', match:92, color:'#388E3C',
    season:'Oct – Mai', water:'250–400 mm', phRange:'6.0–8.0', npk:'N:90 P:45 K:45 kg/ha',
    desc:'Céréale · Tolérant sécheresse' },
  { id:'mais',  name:'Maïs',       emoji:'🌽', cat:'cereale', match:64, color:'#F57F17',
    season:'Avr – Sep', water:'500–800 mm', phRange:'5.8–7.0', npk:'N:180 P:80 K:80 kg/ha',
    desc:'Céréale · Besoin eau élevé' },
  { id:'tomate',name:'Tomate',     emoji:'🍅', cat:'fruit',   match:71, color:'#C62828',
    season:'Mar – Jul', water:'400–600 mm', phRange:'6.0–6.8', npk:'N:100 P:80 K:150 kg/ha',
    desc:'Fruit · Maraîchage · Irrigation' },
  { id:'carotte',name:'Carotte',   emoji:'🥕', cat:'legume',  match:79, color:'#E65100',
    season:'Sep – Mar', water:'300–450 mm', phRange:'6.0–6.8', npk:'N:60 P:60 K:100 kg/ha',
    desc:'Légume racine · Semi-aride OK' },
  { id:'feve',  name:'Fève',       emoji:'🫘', cat:'legumineuse', match:85, color:'#1565C0',
    season:'Nov – Avr', water:'300–400 mm', phRange:'6.0–7.5', npk:'N:20 P:60 K:60 kg/ha',
    desc:'Légumineuse · Fixe azote atmosphérique' },
  { id:'pois',  name:'Pois chiche',emoji:'🫘', cat:'legumineuse', match:90, color:'#0277BD',
    season:'Nov – Avr', water:'250–400 mm', phRange:'5.5–7.5', npk:'N:15 P:50 K:50 kg/ha',
    desc:'Légumineuse · Très adapté semi-aride' },
  { id:'oignon',name:'Oignon',     emoji:'🧅', cat:'legume',  match:68, color:'#6A1B9A',
    season:'Sep – Mar', water:'350–500 mm', phRange:'6.0–7.0', npk:'N:80 P:60 K:80 kg/ha',
    desc:'Légume bulbe · Exportateur K' },
  { id:'olive', name:'Olivier',    emoji:'🫒', cat:'fruit',   match:95, color:'#556B2F',
    season:'Toute l\'année', water:'200–400 mm', phRange:'6.5–8.5', npk:'N:100 P:40 K:120 kg/ha',
    desc:'Arboriculture · Emblème du Maroc' },
  { id:'agrumes', name:'Agrumes',  emoji:'🍊', cat:'fruit',   match:82, color:'#FF8C00',
    season:'Toute l\'année', water:'600–900 mm', phRange:'5.5–7.5', npk:'N:150 P:60 K:150 kg/ha',
    desc:'Fruit · Irrigation nécessaire' },
  { id:'amandier', name:'Amandier', emoji:'🌸', cat:'fruit',   match:89, color:'#FFB6C1',
    season:'Fév – Aoû', water:'250–500 mm', phRange:'7.0–8.5', npk:'N:80 P:40 K:100 kg/ha',
    desc:'Arboriculture · Résistant au calcaire' },
  { id:'dattier', name:'Palmier Dattier', emoji:'🌴', cat:'fruit', match:93, color:'#8B4513',
    season:'Toute l\'année', water:'15000 m³/ha', phRange:'7.0–8.5', npk:'N:120 P:60 K:150 kg/ha',
    desc:'Arboriculture · Tolère la salinité' },
  { id:'lentille', name:'Lentille', emoji:'🍲', cat:'legumineuse', match:87, color:'#A52A2A',
    season:'Nov – Avr', water:'200–350 mm', phRange:'6.0–8.0', npk:'N:20 P:40 K:40 kg/ha',
    desc:'Legumineuse · Rotation de culture' },
  { id:'pdt', name:'Pomme de terre', emoji:'🥔', cat:'legume', match:74, color:'#D2B48C',
    season:'Oct – Mar', water:'400–600 mm', phRange:'5.0–6.5', npk:'N:150 P:100 K:250 kg/ha',
    desc:'Légume · Besoin élevé en Potassium' },
  { id:'betterave', name:'Betterave sucrière', emoji:'🍠', cat:'legume', match:81, color:'#800080',
    season:'Oct – Jui', water:'500–700 mm', phRange:'6.5–8.0', npk:'N:120 P:80 K:200 kg/ha',
    desc:'Culture industrielle · Salino-tolérante' },
];

let currentCultureFilter = 'all';
let selectedCulture = null;
